language: ruby
bundler_args: --jobs=3 --retry=3 --clean --path=bundle
rvm:
  - 2.0
  - 2.1
  - 2.2
gemfile:
  - Gemfile
script:
  - ./bin/rake
  - ./bin/warder --style-guide Gemfile Rakefile warder.gemspec bin/ lib/ features/
  - ./bin/warder --magick-numbers Gemfile Rakefile warder.gemspec bin/ lib/ features/
  - ./bin/warder --code-complexity Gemfile Rakefile warder.gemspec bin/ lib/ features/
  - ./bin/warder --code-smell Gemfile Rakefile warder.gemspec bin/ lib/ features/
  - ./bin/warder --code-duplication Gemfile Rakefile bin/ lib/ features/
  - ./bin/warder --bundle-audit
cache:
  directories:
  - bundle
