language: ruby
rvm:
  - 2.0.0
  - 2.1.0
gemfile:
  - Gemfile
script:
  - bundle exec rake
  - bundle exec warder --style-guide Gemfile Rakefile warder.gemspec bin/ lib/ features/
  - bundle exec warder --magick-numbers Gemfile Rakefile warder.gemspec bin/ lib/ features/
  - bundle exec warder --code-complexity Gemfile Rakefile warder.gemspec bin/ lib/ features/
  - bundle exec warder --code-smells Gemfile Rakefile warder.gemspec bin/ lib/ features/
  - bundle exec warder --code-duplication Gemfile Rakefile bin/ lib/ features/
  - bundle exec warder --bundle-audit
