require 'warder/version'
require 'warder/runner'
require 'warder/style_guide_runner'
require 'warder/magick_numbers_runner'
require 'warder/code_duplications_runner'
require 'warder/code_smells_runner'
require 'warder/cli'
